### PR TITLE
Update user_manual.md

### PR DESCRIPTION
**Pull request by glaforge**
Minor typos :-)

### CODE REVIEW

**Comment by glaforge** [comment]
Now that I've done the PR, I see that someone else did a typo related PR too.
There may be some overlap, sorry!

Anyhow, minicord looks super sweet!!!

**Review by BenjaminPoilve — APPROVED** [review]
A bit of overlap, but a lot of new things, thanks a lot!

**Comment by BenjaminPoilve** [comment]
Thanks a lot, merged!

**Comment by BenjaminPoilve** [comment]
Just for your information, one of the typo you corrected is actually directly from the Chrome Browser:

Screenshot 2024-11-29 at 13 26 29

Seeing that you are working at Google, you might direct that to the Chrome team, with my compliment on the support for WebMIDI that is great :).

**Comment by glaforge** [comment]
I found one occurrence in the Chromium source code with the verb `"reprogramme"`, but that's not the exact label as in the screenshot. But what's interesting is that it was part of localized strings for British English. And in British English, the verb `to program` is spelled `to programme`. So `to reprogram` would be `to reprogramme` in `en-GB`... 
So maybe this one shouldn't be changed (if your locale is indeed in `en-GB`)

**Comment by beaufortfrancois** [comment]
I believe this string comes from https://source.chromium.org/chromium/chromium/src/+/main:components/strings/components_strings_en-GB.xtb;l=2626;drc=1b5a056d259b81a5ec80974aa8791dc1c9135cec
```
<translation id="5723873695528696965">Control and reprogramme your MIDI devices</translation>
```
As noted by @glaforge, this string is used if Chromium uses the `en-GB` language.

According to https://www.collinsdictionary.com/dictionary/english/reprogramme#google_vignette, "reprogramme" Is "another name for reprogram" in British.

**Comment by BenjaminPoilve** [comment]
Yep that's it. A few years ago I swore off my FR locale after a particularly painful afternoon of debugging an issue that was in the end due to our colon use for decimal separation.
So not a typo after all, just a slightly archaic spelling. Thank you both for the investigation :) !

**Pull request merged**
